config/routes.rb
Rails.application.routes.draw do
  resources :supports do
    member do
      patch "upvote", to: "supports#upvote"
      patch "downvote", to: "supports#downvote"
    end
  end

  resources :ratings

  devise_for :users

  resources :users, :only => [:show]

  resources :posts

  root 'posts#index'
end
 

app/controllers/home_controller.rb
class HomeController < ApplicationController

before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def profile
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        
    
            <%= link_to image_tag("second_rate_logo.png", width: 50, class:"navbar-brand"), root_path%>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to "Profile", current_user, class:"nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to '+ New Post', new_post_path, class:"nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link" %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                        </li>

                        <li class="nav-item">
                            <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
                        </li>
                    <% end %>
             
                </ul>

                <li class="nav-item navbar-nav mb-2 mb-lg-0">
                    <%= link_to "Support", supports_path, class:"nav-link" %>
                </li>

                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
       
    </div>
</nav>

app/views/home/index.html.erb
<h1>Home Page</h1>