config/routes.rb
Rails.application.routes.draw do
  resources :supports do
    member do
      patch "upvote", to: "supports#upvote"
      patch "downvote", to: "supports#downvote"
    end
  end

  resources :ratings

  devise_for :users

  resources :users, :only => [:show]

  resources :posts

  root 'posts#index'
end
 

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    has_many :ratings
    has_rich_text :content
    belongs_to :user

    #validations
    validates :image, presence: true
    validates :name, presence: true
    validates :iso, presence: true
    validates :shutter_speed, presence: true
    validates :appature, presence: true
    validates :composition, presence: true
    validates :location, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.joins('LEFT JOIN (SELECT post_id, AVG(rating) avg_rating, COUNT(rating) rating_count FROM ratings GROUP BY post_id) r ON r.post_id = posts.id').order('r.avg_rating DESC, r.rating_count DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show
    @posts = Post.joins('LEFT JOIN (SELECT post_id, AVG(rating) avg_rating, COUNT(rating) rating_count FROM ratings GROUP BY post_id) r ON r.post_id = posts.id').order('r.avg_rating DESC, r.rating_count DESC')

    @rating_user_id = Rating.where("post_id = ?", params[:id]).select( "user_id, rating")
    @post = Post.find(params[:id])
    
    if @post.ratings.all.average(:rating)
      @rate = (@post.ratings.all.average(:rating)).round(2)
    else
      @rate = @post.ratings.all.average(:rating)
    end

    @ratecount = @post.ratings.all.count(:rating)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    
    respond_to do |format|
      if @post.update(post_params)

        @rating = Rating.find_or_create_by(user: current_user, post: @post, rating: params[:ratings])
        @rating.save!

        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "You do not have permission to modify this post" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {}).permit(:name, :iso, :shutter_speed, :appature, :composition, :location, :description, :image, :user_id, ratings_attributes: [:rating])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_rated_users(query)
        array = []
        query.each do |row|
            array << row['user_id']
        end
        return array
    end

    def already_post_rating(query)
        rating = 0
        query.each do |row|
            if row['user_id'] == current_user.id
                rating = row['rating']
            end
        end
        return rating
    end

    def nxt(nxt)
        if nxt = "nxt"
            @posts.each.with_index do |post,index|
                if @post.id == post.id && index <= @posts.length 
                    return @posts[0] if @posts[index] == @posts.last 
                    return @posts[index + 1]
                end
            end
        end
    end

    def prev(prev)
        if prev = "prev"
            @posts.each_with_index do |post,index|
                if @post.id == post.id && index >= 0
                    return @posts[index - 1]
                end
            end
        end
    end

end

app/views/posts/_form.html.erb
</br>
</br>
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <% post.errors.each do |error| %>
      <div id="error_explanation" class="alert alert-warning alert-dismissible fade show">
          <%= error.full_message %></li>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  <% end %>
  <div class="col align-self-center card">
    <div class="card-header text-center">
      + New Post
    </div>
    <div class="card-body">        
      <div class="field form-group mb-3">
        <div class="field form-group text-center mb-3">
          <%= form.file_field :image, class:"form-control mb-4", placeholder:"Choose an Image" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_field :name, class:"form-control", placeholder:"Name the post (something short)" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_field :iso, class:"form-control", placeholder:"ISO Number" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_field :shutter_speed, class:"form-control", placeholder:"Shutter Speed (1/200)" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_field :appature, class:"form-control", placeholder:"Appature Decimal (4.0)" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_field :composition, class:"form-control", placeholder:"Composition: Rule of third, centered, foreground, etc" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_field :location, class:"form-control", placeholder:"Photo Location: Seattle, New York, China" %>
        </div>

        <div class="field form-group mb-3">
          <%= form.text_area :description, class:"form-control", placeholder:"Breif Description/More Information." %>
        </div>

        <div class="field form-group mb-3">
          <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value:current_user.id, type: :hidden%>
        </div>

        <div class="actions d-grid gap-2 mb-3"">
          <%= form.submit class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_rating.html.erb
<div class="col align-self-center card mb-3">   
        <%= form_for [@post] do |f| %>
            <div class="card-body text-center">        
                <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                    <%= f.radio_button :ratings, 1, :type => "radio", :class => "btn-check", :name => "ratings", :id => "btnradio1", :autocomplete => "off" %>
                    <%= f.label :ratings, "1", :value => 1, :class => "btn btn-outline-danger",  :for => "btnradio1"  %>
                    
                    <%= f.radio_button :ratings, 2, :type => "radio", :class => "btn-check", :name => "ratings", :id => "btnradio2", :autocomplete => "off" %>
                    <%= f.label :ratings, "2", :value => 2, :class => "btn btn-outline-warning",  :for => "btnradio2"  %>
                    
                    <%= f.radio_button :ratings, 3, :type => "radio", :class => "btn-check", :name => "ratings", :id => "btnradio3", :autocomplete => "off" %>
                    <%= f.label :ratings, "3", :value => 3, :class => "btn btn-outline-success",  :for => "btnradio3"  %>
                    
                    <%= f.radio_button :ratings, 4, :type => "radio", :class => "btn-check", :name => "ratings", :id => "btnradio4", :autocomplete => "off" %>
                    <%= f.label :ratings, "4", :value => 4, :class => "btn btn-outline-info",  :for => "btnradio4"  %>
                    
                    <%= f.radio_button :ratings, 5, :type => "radio", :class => "btn-check", :name => "ratings", :id => "btnradio5", :autocomplete => "off" %>
                    <%= f.label :ratings, "5", :value => 5, :class => "btn btn-outline-primary",  :for => "btnradio5"  %>        
                </div>
            </div>

            <div class="card-footer">
                <div class="actions d-grid gap-2 mb-3">
                    <%=f.submit "Rate This Photo", :class => "btn btn-secondary" %>
                </div>
            </div>
        <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
</br>
<div class="container">
    <div class="row justify-content-start">
        <div class="col">
            <%= link_to '+ New Post', new_post_path, class:"btn btn-secondary mb-3" %>
        </div>
    </div>

    <div class="row">
        <% @posts.each do |post| %>
            <div class="col-md-auto">
                <%= link_to image_tag(post.image, class:"img mb-4"), post %> 
            </div>
        <% end %>       
    </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"nav-link" %>

app/views/posts/show.html.erb
</br>
<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="card text-center">
        <div class="card-footer">
          <%= "Rating: #{@rate} (#{@ratecount})" %>
        </div>
        <div class="card-body">
          <%= image_tag @post.image, style: "max-width: 100%; min-width: 300px;}" %>
        </div>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="row">
        <div class="col">
          <%= link_to "", prev("prev"), class: "bi bi-arrow-left", style: "font-size: 3rem; color: cornflowerblue;" %>
        </div>
        <div class="col text-end">
          <%= link_to "", nxt("nxt") , class: "bi bi-arrow-right", style: "font-size: 3rem; color: cornflowerblue;" %>
        </div>
      </div>
      <% if user_signed_in? %>
        <% if !post_rated_users(@rating_user_id).include?(current_user.id) %>
          <%= render 'rating', post: @post %>
        <% elsif  post_rated_users(@rating_user_id).include?(current_user.id) %>
          <div class="card-footer text-center mb-3">
            <%= "You have already gave this post a #{already_post_rating(@rating_user_id)} rating"%>
          </div>
        <% end %> 
      <% elsif !user_signed_in? %>      
        <div class="card-footer text-center">
          Please sign in to rate some photos 
          <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
        </div>   
      <% end %> 
      <table class="table table-striped">
        <tbody>
          <tr>
            <th scope="row">Name</th>
            <td><%= @post.name %></td>
          </tr>
          <tr>
            <th scope="row">ISO</th>
            <td><%= @post.iso %></td>
          </tr>
          <tr>
            <th scope="row">Shutter speed</th>
            <td><%= @post.shutter_speed %></td>
          </tr>
          <tr> 
            <th scope="row">Appature</th>
            <td><%= @post.appature %></td>
          </tr>
          <tr>
            <th scope="row">Composition</th>
            <td><%= @post.composition %></td>
          </tr>
          <tr>
            <th scope="row">Location</th>
            <td><%= @post.location %></td>
          </tr>
          <tr>
            <th scope="row">Description</th>
            <td><%= @post.description %></td>
          </tr>
          <tr>
            <th scope="row">Photographer</th>
            <td>
              <%= link_to name(@post.user_id), user_path(@post.user_id), class:"nounderline"%>
            </td>
          </tr>
          <% if user_signed_in? && @post.user_id == current_user.id%>
            <tr>
              <td colspan="2">
                <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-secondary" %>
                <%= link_to 'Delete', @post, :method => :delete, :confirm => "Are you sure?", class:"btn btn-danger" %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>      
    </div>
  </div>
</div>