config/routes.rb
Rails.application.routes.draw do
  resources :supports do
    member do
      patch "upvote", to: "supports#upvote"
      patch "downvote", to: "supports#downvote"
    end
  end

  resources :ratings

  devise_for :users

  resources :users, :only => [:show]

  resources :posts

  root 'posts#index'
end
 

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :user
  has_rich_text :body

  acts_as_votable

  validates :support_type, presence: true
  validates :body, presence: true
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :set_support, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :destroy]

  # GET /supports or /supports.json
  def index
    @supports = Support.all.order(status: :asc, cached_votes_score: :desc, support_type: :asc)
  end

  def upvote
    @support = Support.find(params[:id])

    if current_user.voted_up_on? @support
      if current_user.admin
        @support.unvote_by current_user
        @support.update(status: "Pending")
      else
        @support.unvote_by current_user
      end
    else
      if current_user.admin
        @support.upvote_by current_user
        @support.update(status: "Resolved")
      else
        @support.upvote_by current_user
      end      
    end
    render "vote.js.erb"
  end

  def downvote
    @support = Support.find(params[:id])

    if current_user.voted_down_on? @support
      if current_user.admin
        @support.unvote_by current_user
        @support.update(status: "Pending")
      else
        @support.unvote_by current_user
      end  
    else
      if current_user.admin
        @support.downvote_by current_user
        @support.update(status: "Rejected")
      else
        @support.downvote_by current_user
      end
    end
    render "vote.js.erb"
  end

  # GET /supports/1 or /supports/1.json
  def show
    @support = Support.find(params[:id])
  end

  # GET /supports/new
  def new
    @support = current_user.supports.new
  end

  # GET /supports/1/edit
  def edit
  end

  # POST /supports or /supports.json
  def create
    @support = current_user.supports.build(support_params)
    @support.update(content: @support.body.to_plain_text)

    respond_to do |format|
      if @support.save
        format.html { redirect_to @support, notice: "Support was successfully created." }
        format.json { render :show, status: :created, location: @support }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supports/1 or /supports/1.json
  def update
    respond_to do |format|
      if @support.update(support_params)
        format.html { redirect_to @support, notice: "Support was successfully updated." }
        format.json { render :show, status: :ok, location: @support }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1 or /supports/1.json
  def destroy
    @support.destroy
    respond_to do |format|
      format.html { redirect_to supports_url, notice: "Support was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @support = current_user.supports.find_by(id: params[:id])
    redirect_to supports_path, notice: "You do not have permission to modify this post" if @support.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support
      @support = Support.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def support_params
      params.require(:support).permit(:support_type, :content, :user_id, :body)
    end
end

app/helpers/supports_helper.rb
module SupportsHelper
    def status(support_id)
        support = Support.find(support_id)
        if support.status == "Resolved"
            return badge = content_tag(:i, " #{support.status}" , class: ["bi", "bi-check-circle-fill"], style: ["font-size: 1.2rem;", "color: green;"])  
        elsif support.status == "Rejected"
            return badge = content_tag(:i, " #{support.status}" , class: ["bi", "bi-x-circle-fill"], style: ["font-size: 1.2rem;", "color: red;"])   
        else
           return badge = content_tag(:i, " #{support.status}" , class: ["bi", "bi-pause-circle-fill"], style: ["font-size: 1.2rem;", "color: orange;"])                       
        end
    end
end

app/views/supports/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{support.id}" do %>
  <%= link_to downvote_support_path(support), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if current_user.voted_down_on? support %>
      <i class="bi bi-hand-thumbs-down-fill", style="font-size: 1.5rem;"></i>
    <% else %>
      <i class="bi bi-hand-thumbs-down", style="font-size: 1.5rem;"></i>
    <% end %>
  <% end %>
<% end %>

app/views/supports/_form.html.erb
<%= form_with(model: support) do |form| %>
  <% if support.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(support.errors.count, "error") %> prohibited this support from being saved:</h2>

      <ul>
        <% support.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.select :support_type, options_for_select([["Select Support Type", ""], "Report a Bug", "Ask a Question", "Request a Feature", "Other"]), class: "form-select", id:"exampleFormControlInput1" %>
  </div>

  <div class="mb-3" data-controller="trix">
    <%= form.rich_text_area :body, class:"form-control", id:"exampleFormControlTextarea1", rows:"3", placeholder:"Please provide as much details as possible"  %>
  </div>

  <div class="field form-group mb-3">
    <%= form.number_field :user_id, id: :support_user_id, class:"form-control", value:current_user.id, type: :hidden%>
  </div>

  <div class="actions d-grid gap-2 mb-3"">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/supports/_like_count.html.erb
<%= content_tag "div", id: "like-count-#{support.id}" do %>
  <%= support.cached_votes_score %>
<% end %>

app/views/supports/_support.html.erb
<div id="<%= dom_id support %>">
  <div class="card mb-5">
    <div class="card-header">
      <div class="row">
        <div class="col">
          <%= support.name %>
        </div>
        <div class="col text-end">
          From: <%= link_to "#{User.find(support.user_id).first_name} #{User.find(support.user_id).last_name}", user_path(support.id), class:"nounderline"%>
        </div>
      </div>
    </div>
    <div class="card-body">
      <%= support.content %>
    </div>
    <div class="card-footer text-muted">
      <div class="row">
        <div class="col">
          <%= link_to "Show this support", support, class:"btn btn-outline-secondary btn-sm" %>
        </div>
        <div class="col text-end">
          Posted <%= time_tag support.created_at, "data-local": "time-ago" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/supports/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{support.id}" do %>
  <%= link_to upvote_support_path(support), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if current_user.voted_up_on? support %>
      <i class="bi bi-hand-thumbs-up-fill", style="font-size: 1.5rem;"></i>
    <% else %>
      <i class="bi bi-hand-thumbs-up", style="font-size: 1.5rem;"></i>
    <% end %>
  <% end %>
<% end %>

app/views/supports/edit.html.erb
</br>
</br>
<%= link_to "Back to supports", supports_path, class: "nounderline bi bi-arrow-left mb-3", style: "font-size: 1.2rem; color: cornflowerblue;" %>
</br>
</br>
<%= render 'form', support: @support %>

app/views/supports/index.html.erb
</br>
</br>
<% if user_signed_in? %>
  <%= link_to '+ New Support Post', new_support_path, class:"btn btn-secondary mb-3" %>
  <% @supports.each do |support| %>  
    <div class="row mb-4 align-items-start">
      <div class="col-auto ">
        <div class="col text-center ">
          <% if current_user && support.status == "Pending" && !current_user.admin%>
            <%= render 'supports/upvote_link', support: support %>
            <%= render 'supports/like_count', support: support %>
            <%= render 'supports/downvote_link', support: support %>
          <% elsif current_user %>
            <% if current_user.admin %>
              <%= render 'supports/upvote_link', support: support %>
              <%= render 'supports/like_count', support: support %>
              <%= render 'supports/downvote_link', support: support %>
            <% end %>
          <% end %>
        </div>
      </div>

      <% if !current_user.admin && (support.status == "Pending" || support.status == "Resolved") %>
        <div class="col">
          <div class="card">
            <div class="card-header">
              <div class="row">
                <div class="col">
                  <%= support.support_type %>
                </div>
                <div class="col text-center">
                  <%= status(support.id) %>
                </div>
                <div class="col text-end">
                  <%= link_to name(support.user_id), user_path(support.user_id), class:"nounderline"%>
                </div>
              </div>
            </div>

            <div class="card-body">
              <%= support.body %></br>
            </div>

            <div class="card-footer text-muted">
              <div class="row">
                <div class="col">
                  <%= link_to "Show this support", support, class:"btn btn-outline-secondary btn-sm" %>
                </div>
                <div class="col text-center">
                  < <%= support.id %> >
                </div>
                <div class="col text-end">
                  Published <%= local_time_ago(support.created_at) %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>  
        
      <% if current_user.admin%>
        <div class="col">
          <div class="card">
            <div class="card-header">
              <div class="row">
                <div class="col">
                  <%= support.support_type %>
                </div>
                <div class="col text-center">
                  <%= status(support.id) %>
                </div>
                <div class="col text-end">
                  <%= link_to name(support.user_id), user_path(support.user_id), class:"nounderline"%>
                </div>
              </div>
            </div>

            <div class="card-body">
              <%= support.body %></br>
            </div>

            <div class="card-footer text-muted">
              <div class="row">
                <div class="col">
                  <%= link_to "Show this support", support, class:"btn btn-outline-secondary btn-sm" %>
                </div>
                <div class="col text-center">
                  < <%= support.id %> >
                </div>
                <div class="col text-end">
                  Published <%= local_time_ago(support.created_at) %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>  
        
    </div>
  <% end %>
<% else %>
  <div class="card text-center" style="background-color: lightgray;">
    Please sign in to view the content of this page 
    <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
  </div>  
<% end %>

app/views/supports/new.html.erb
<h1>New Support</h1>

<%= render 'form', support: @support %>

<%= link_to 'Back', supports_path %>

app/views/supports/show.html.erb
</br>
</br>
<%= link_to "Back to supports", supports_path, class: "nounderline bi bi-arrow-left mb-3", style: "font-size: 1.2rem; color: cornflowerblue;" %>
</br>
</br>
<div class="card mb-5">
  <div class="card-header">
    <div class="row">
      <div class="col">
        <%= @support.support_type %>
      </div>
      <div class="col text-center">
        <%= status(@support.id) %>
      </div>
      <div class="col text-end">
        <%= link_to name(@support.user_id), user_path(@support.user_id), class:"nounderline"%>
      </div>
    </div>
  </div>

  <div class="card-body">
    <%= @support.body %>
  </div>

  <div class="card-footer text-muted">
    <div class="row">
      <div class="col">
        <%#= link_to "Show this support", support, class:"btn btn-outline-secondary btn-sm" %>
      </div>
      <div class="col text-center">
        < <%= @support.id %> >
      </div>
      <div class="col text-end">
        Posted: <%= time_tag @support.created_at, "data-local": "time-ago" %>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? && @support.user_id == current_user.id%>
  <%= link_to 'Edit', edit_support_path(@support), class:"btn btn-outline-secondary" %>
  <%= link_to 'Delete', @support, :method => :delete, :confirm => "Are you sure?", class:"btn btn-outline-danger" %>
<% end %>

app/views/supports/vote.js.erb
document.getElementById("like-count-<%= @support.id %>").innerHTML = "<%= j render "supports/like_count", support: @support %>";
document.getElementById("downvote-<%= @support.id %>").innerHTML = "<%= j render "supports/downvote_link", support: @support %>";
document.getElementById("upvote-<%= @support.id %>").innerHTML = "<%= j render "supports/upvote_link", support: @support %>";